kind: Application
metadata:
  name: elastic-agent
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/Latsayya/elastic-k8s-gitops
    targetRevision: main
    path: helm/elastic-agent
    helm:
      chart: elastic-agent
      repoURL: https://helm.elastic.co
      valueFiles:
        - values.yaml

  destination:
    server: https://kubernetes.default.svc
    namespace: elastic-agent

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
